# Generated by Django 4.1.2 on 2022-11-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default_profile.png', upload_to='static/img', verbose_name='photo de profil'),
        ),
    ]
